MACHINE=
SCRIPT_NAME=wasm64
OUTPUT_FORMAT="elf64-wasm64"
TEXT_START_ADDR=0x4000000000001000
TEMPLATE_NAME=elf32

DATA_START_SYMBOLS='__data_start = . ;';

GENERATE_SHLIB_SCRIPT=yes

ARCH=wasm64
MACHINE=
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ENTRY=_start

NO_SMALL_DATA=yes
