MACHINE=
SCRIPT_NAME=wasm
OUTPUT_FORMAT="elf32-wasm"
TEXT_START_ADDR=0x40001000
TEMPLATE_NAME=elf32

DATA_START_SYMBOLS='__data_start = . ;';

GENERATE_SHLIB_SCRIPT=yes

ARCH=wasm
MACHINE=
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ENTRY=_start

NO_SMALL_DATA=yes
