MACHINE=
SCRIPT_NAME=wasm32
OUTPUT_FORMAT="elf32-wasm32"
TEXT_START_ADDR=0x40001000
TEMPLATE_NAME=elf

DATA_START_SYMBOLS='__data_start = . ;';

GENERATE_SHLIB_SCRIPT=yes

ARCH=wasm32
MACHINE=
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ENTRY=_start

NO_SMALL_DATA=yes
